FROM apache/airflow:2.7.3

USER root

# Instalar dependencias del sistema si son necesarias (ej: para psycopg2)
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         build-essential \
         libpq-dev \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow

# Copiar requirements del scraper para tener las mismas dependencias
COPY scraper-service/requirements.txt /requirements.txt

# Instalar dependencias
RUN pip install --no-cache-dir -r /requirements.txt
